! %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
! Copyright (c) 2026, University of Maryland Baltimore County
! All rights reserved.
!
! Redistribution and use in source and binary forms, with or without modification, are
! permitted provided that the following conditions are met:
!
! 1. Redistributions of source code must retain the above copyright notice, this list of
!    conditions and the following disclaimer.
!
! 2. Redistributions in binary form must reproduce the above copyright notice, this list
!    of conditions and the following disclaimer in the documentation and/or other
!    materials provided with the distribution.
!
! 3. Neither the name of the copyright holder nor the names of its contributors may be
!    used to endorse or promote products derived from this software without specific prior
!    written permission.
!
! THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
! EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
! MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
! THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
! SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
! OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
! INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
! LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
! OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
!
! History
! Sep 2026: Initial version of the HARP2 (PACE) polarimetric cloudbow simulator
! %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!
! Notes on using the HARP2 simulator:
!  *) The simulator mimics the polarimetric ("cloudbow") retrieval of the liquid-cloud
!     droplet effective radius (re) and effective variance (ve) from the multi-angle
!     polarized reflectance measured by HARP2 in its hyper-angular 670 nm band.
!  *) Forward model: for every subcolumn the polarized reflectance Rp is computed in the
!     single-scattering approximation for a plane-parallel stack of layers containing
!     liquid droplets, ice crystals and air molecules, over a black surface:
!
!       Rp(j) = 1/(4(mu_j+mu0)) * sum_k [ S_k(Theta_j)/dtau_k ] * exp(-tau_k^top m_j)
!                                             * [1 - exp(-dtau_k m_j)]
!
!     with S_k = dtauLiq_k ssa_k (-P12_liq(Theta; re_k, ve_k)) + dtauRay_k (-P12_ray(Theta))
!     and m_j = 1/mu_j + 1/mu0. Polarization of multiply-scattered light is neglected,
!     which is a good approximation for the cloudbow (Breon and Goloub 1998). Ice
!     crystals attenuate but are assumed to produce no polarized signal.
!  *) Retrieval: the geometry-normalized signal 4(mu_j+mu0)Rp(j) is fitted, over the
!     scattering-angle window [cloudbow_ThetaMin, cloudbow_ThetaMax], with the parametric
!     model of Breon and Goloub (1998)
!
!       A * (-P12_liq(Theta; re, ve)) + B cos^2(Theta) + C,
!
!     where A, B, C are found by linear least squares for every (re, ve) node of the Mie
!     look-up table and (re, ve) minimizes the residual. The smooth terms B and C absorb
!     the Rayleigh contribution. The minimum is refined by parabolic interpolation.
!  *) Because the polarized signal comes from single scattering, the retrieved re and ve
!     are weighted toward the top ~1/m_j (a few tenths) of optical depth of the cloud,
!     and vertical variations of re broaden the retrieved ve.
!  *) The look-up table of -P12 is generated by harp2_lut_generator.py (miepython) and is
!     loaded by cosp_harp2_init in cosp_harp2_interface.F90.
!  *) Particle sizes are input in microns; retrieved radii are reported in meters, as for
!     the MODIS simulator.
!
! References:
!  Breon, F.-M., and P. Goloub, 1998: Cloud droplet effective radius from spaceborne
!     polarization measurements. Geophys. Res. Lett., 25, 1879-1882.
!  Hansen, J. E., and L. D. Travis, 1974: Light scattering in planetary atmospheres.
!     Space Sci. Rev., 16, 527-610.
!
module mod_harp2_sim
  USE MOD_COSP_CONFIG, only: R_UNDEF,numHARP2ReffBins,numHARP2VeffBins,                 &
                             harp2_histReff,harp2_histVeff
  USE COSP_KINDS,      ONLY: wp
  USE COSP_MATH_CONSTANTS, ONLY: pi
  use MOD_COSP_STATS,  ONLY: hist2D

  implicit none
  ! ##########################################################################
  ! Retrieval parameters (set in cosp_harp2_init)
  real(wp) :: &
       min_OpticalThickness,          & ! Minimum column optical thickness for a retrieval
       cloudbow_ThetaMin,             & ! Lower edge of the cloudbow fitting window (deg)
       cloudbow_ThetaMax,             & ! Upper edge of the cloudbow fitting window (deg)
       cloudbow_AmplitudeMin,         & ! Minimum fitted cloudbow amplitude A (relative to an
                                        ! optically thick unobscured liquid cloud) needed to
                                        ! detect the cloudbow
       fit_QualityMin,                & ! Minimum fraction of the non-smooth signal explained
                                        ! by the cloudbow term
       rayleigh_OpticalDepth,         & ! Column Rayleigh optical depth at 1013.25 hPa
       rayleigh_Depolarization          ! Rayleigh depolarization factor (1-rho)/(1+rho/2)
  integer :: &
       min_NumAnglesInWindow            ! Minimum number of view angles inside the window
  logical :: &
       include_Rayleigh                 ! Include molecular scattering in the forward model

  ! Retrieval outcome flags (subcolumn)
  integer,parameter :: &
       harp2_flagClear       = 0,     & ! Column optical thickness below detection threshold
       harp2_flagCloudbow    = 1,     & ! Successful liquid cloudbow retrieval
       harp2_flagNoCloudbow  = 2,     & ! Cloudy, but no cloudbow detected (e.g. ice topped)
       harp2_flagGeometry    = 3,     & ! Cloudy, but the cloudbow window is not sampled
       harp2_flagFitFailed   = 4        ! Cloudbow detected, but the fit failed (poor fit
                                        ! or radius at the edge of the look-up table)

  ! Polarized phase function look-up table (loaded by cosp_harp2_init)
  integer :: &
       nLUT_theta = 0,                & ! Number of scattering angles
       nLUT_re    = 0,                & ! Number of effective radii
       nLUT_ve    = 0                   ! Number of effective variances
  real(wp) :: &
       LUT_wavelength                   ! Wavelength (microns)
  real(wp),allocatable,dimension(:) :: &
       LUT_theta,                     & ! Scattering angle (deg), uniformly spaced
       LUT_re,                        & ! Effective radius (microns), uniformly spaced
       LUT_ve                           ! Effective variance, increasing
  real(wp),allocatable,dimension(:,:) :: &
       LUT_ssa                          ! Single-scattering albedo (re,ve)
  real(wp),allocatable,dimension(:,:,:) :: &
       LUT_mP12                         ! -P12 (theta,re,ve), (1/4pi) int(P11) = 1

contains
  ! ########################################################################################
  ! HARP2 subcolumn simulator: forward model and cloudbow retrieval for all subcolumns of
  ! one grid point. All subcolumns share the viewing geometry.
  ! ########################################################################################
  subroutine harp2_subcolumn(nSubCols, nLevels, nAngles, mu0, muView, scatAngle,         &
                             pressureLevels, optical_thickness, tauLiquidFraction,        &
                             reffLiq, veffLiq, retrievedFlag, retrievedSize,              &
                             retrievedVariance, polarizedReflectance)
    ! INPUTS
    integer,intent(in) :: &
         nSubCols,                  & ! Number of subcolumns
         nLevels,                   & ! Number of levels (1 = top of atmosphere)
         nAngles                      ! Number of viewing angles
    real(wp),intent(in) :: &
         mu0                          ! Cosine of the solar zenith angle
    real(wp),dimension(nAngles),intent(in) :: &
         muView,                    & ! Cosine of the view zenith angles
         scatAngle                    ! Scattering angles (degrees)
    real(wp),dimension(nLevels+1),intent(in) :: &
         pressureLevels               ! Pressure at layer edges (Pa)
    real(wp),dimension(nSubCols,nLevels),intent(in) :: &
         optical_thickness,         & ! Subcolumn optical thickness @ 0.67 microns
         tauLiquidFraction,         & ! Fraction of optical thickness due to liquid
         reffLiq,                   & ! Liquid effective radius (microns)
         veffLiq                      ! Liquid effective variance

    ! OUTPUTS
    integer, dimension(nSubCols), intent(out) :: &
         retrievedFlag                ! Retrieval outcome (harp2_flag*)
    real(wp),dimension(nSubCols), intent(out) :: &
         retrievedSize,             & ! Retrieved effective radius (meters)
         retrievedVariance            ! Retrieved effective variance
    real(wp),dimension(nSubCols,nAngles),intent(out),optional :: &
         polarizedReflectance         ! Simulated polarized reflectance (R_UNDEF outside
                                      ! the cloudbow window)

    ! LOCAL VARIABLES
    integer :: i, k, nWin
    integer,dimension(nAngles) :: iWin
    real(wp),allocatable,dimension(:) :: &
         airMass, geoNorm, mP12Ray, basis1, basis2, Rp, z
    real(wp),allocatable,dimension(:,:,:) :: &
         F, Ftil
    real(wp),dimension(nLUT_re,nLUT_ve) :: &
         FtilNorm2
    real(wp),dimension(nLevels) :: &
         tauLiq, tauIce, tauRay

    retrievedFlag(1:nSubCols)     = harp2_flagClear
    retrievedSize(1:nSubCols)     = R_UNDEF
    retrievedVariance(1:nSubCols) = R_UNDEF
    if (present(polarizedReflectance)) polarizedReflectance(1:nSubCols,1:nAngles) = R_UNDEF

    ! ######################################################################################
    ! Geometry: select the view angles inside the cloudbow window. Everything computed in
    ! this section depends only on the geometry and is shared by all subcolumns.
    ! ######################################################################################
    nWin = 0
    do k = 1, nAngles
       if (scatAngle(k) >= cloudbow_ThetaMin .and. scatAngle(k) <= cloudbow_ThetaMax .and. &
           scatAngle(k) >= LUT_theta(1) .and. scatAngle(k) <= LUT_theta(nLUT_theta)) then
          nWin = nWin + 1
          iWin(nWin) = k
       endif
    enddo

    if (nWin < max(min_NumAnglesInWindow, 4)) then
       ! The cloudbow is not observed: flag the cloudy subcolumns
       do i = 1, nSubCols
          if (sum(optical_thickness(i,1:nLevels)) >= min_OpticalThickness)             &
               retrievedFlag(i) = harp2_flagGeometry
       enddo
       return
    endif

    allocate(airMass(nWin), geoNorm(nWin), mP12Ray(nWin), basis1(nWin), basis2(nWin),    &
             Rp(nWin), z(nWin), F(nWin,nLUT_re,nLUT_ve), Ftil(nWin,nLUT_re,nLUT_ve))
    airMass(1:nWin) = 1._wp/muView(iWin(1:nWin)) + 1._wp/mu0
    geoNorm(1:nWin) = 4._wp*(muView(iWin(1:nWin)) + mu0)
    mP12Ray(1:nWin) = 0.75_wp*rayleigh_Depolarization*sin(scatAngle(iWin(1:nWin))*pi/180._wp)**2

    ! Orthonormal basis of the smooth terms {1, cos^2(Theta)} of the parametric fit
    call smooth_basis(nWin, scatAngle(iWin(1:nWin)), basis1, basis2)

    ! -P12 of every LUT node at the window angles, and its projection orthogonal to the
    ! smooth terms (used by the linear least-squares fit)
    call lut_at_angles(nWin, scatAngle(iWin(1:nWin)), F)
    call remove_smooth(nWin, nLUT_re*nLUT_ve, basis1, basis2, F, Ftil)
    FtilNorm2(1:nLUT_re,1:nLUT_ve) = sum(Ftil(1:nWin,1:nLUT_re,1:nLUT_ve)**2, dim = 1)

    ! Molecular optical depth of each layer
    tauRay(1:nLevels) = 0._wp
    if (include_Rayleigh) tauRay(1:nLevels) = rayleigh_OpticalDepth *                    &
         abs(pressureLevels(2:nLevels+1) - pressureLevels(1:nLevels)) / 101325._wp

    ! ######################################################################################
    ! Loop over subcolumns
    ! ######################################################################################
    do i = 1, nSubCols
       ! Cloud detection
       if (sum(optical_thickness(i,1:nLevels)) < min_OpticalThickness) cycle

       ! Forward model: single-scattering polarized reflectance
       tauLiq(1:nLevels) = optical_thickness(i,1:nLevels)*tauLiquidFraction(i,1:nLevels)
       tauIce(1:nLevels) = optical_thickness(i,1:nLevels) - tauLiq(1:nLevels)
       call single_scattering_polarized_reflectance(nLevels, nWin, tauLiq, tauIce, tauRay, &
            reffLiq(i,1:nLevels), veffLiq(i,1:nLevels), airMass, geoNorm, mP12Ray, F, Rp)
       if (present(polarizedReflectance)) polarizedReflectance(i,iWin(1:nWin)) = Rp(1:nWin)

       ! Retrieval: fit the geometry-normalized signal
       z(1:nWin) = geoNorm(1:nWin)*Rp(1:nWin)
       call cloudbow_retrieval(nWin, z, basis1, basis2, Ftil, FtilNorm2,                 &
                               retrievedFlag(i), retrievedSize(i), retrievedVariance(i))
       if (retrievedFlag(i) == harp2_flagCloudbow) retrievedSize(i) = 1.0e-06_wp*retrievedSize(i)
    enddo

    deallocate(airMass, geoNorm, mP12Ray, basis1, basis2, Rp, z, F, Ftil)

  end subroutine harp2_subcolumn

  ! ########################################################################################
  ! Grid-box statistics
  ! ########################################################################################
  subroutine harp2_column(nPoints, nSubCols, flag, particle_size, size_variance,         &
                          Cloud_Fraction_Liquid_Mean, Cloud_Particle_Size_Liquid_Mean,    &
                          Effective_Variance_Liquid_Mean, Reff_vs_Veff_Liquid)
    ! INPUTS
    integer,intent(in) :: &
         nPoints,                           & ! Number of horizontal gridpoints
         nSubCols                             ! Number of subcolumns
    integer,intent(in), dimension(nPoints, nSubCols) ::  &
         flag                                 ! Subcolumn retrieval outcome
    real(wp),intent(in),dimension(nPoints, nSubCols) ::  &
         particle_size,                     & ! Retrieved effective radius (m)
         size_variance                        ! Retrieved effective variance
    ! OUTPUTS
    real(wp),intent(inout),dimension(nPoints) :: &
         Cloud_Fraction_Liquid_Mean,        & ! Fraction of subcolumns with cloudbow retrieval (%)
         Cloud_Particle_Size_Liquid_Mean,   & ! Mean retrieved effective radius (m)
         Effective_Variance_Liquid_Mean       ! Mean retrieved effective variance
    real(wp),intent(inout),dimension(nPoints,numHARP2ReffBins,numHARP2VeffBins) :: &
         Reff_vs_Veff_Liquid                  ! Joint histogram of re and ve (%)
    ! LOCAL VARIABLES
    integer :: j
    logical, dimension(nPoints,nSubCols) :: validMask
    real(wp),dimension(nSubCols) :: reWRK, veWRK
    real(wp),dimension(nPoints) :: nValid

    validMask(1:nPoints,1:nSubCols) = flag(1:nPoints,1:nSubCols) == harp2_flagCloudbow
    nValid(1:nPoints) = real(count(validMask, dim = 2), wp)

    where(nValid(1:nPoints) > 0)
       Cloud_Particle_Size_Liquid_Mean(1:nPoints) = sum(particle_size, mask = validMask,  &
            dim = 2) / nValid(1:nPoints)
       Effective_Variance_Liquid_Mean(1:nPoints)  = sum(size_variance, mask = validMask,  &
            dim = 2) / nValid(1:nPoints)
    elsewhere
       Cloud_Particle_Size_Liquid_Mean(1:nPoints) = R_UNDEF
       Effective_Variance_Liquid_Mean(1:nPoints)  = R_UNDEF
    endwhere
    Cloud_Fraction_Liquid_Mean(1:nPoints) = 100._wp*nValid(1:nPoints)/nSubCols

    do j = 1, nPoints
       reWRK(1:nSubCols) = merge(particle_size(j,1:nSubCols), -999._wp, validMask(j,1:nSubCols))
       veWRK(1:nSubCols) = merge(size_variance(j,1:nSubCols), -999._wp, validMask(j,1:nSubCols))
       call hist2D(reWRK, veWRK, nSubCols, harp2_histReff, numHARP2ReffBins,              &
                   harp2_histVeff, numHARP2VeffBins,                                      &
                   Reff_vs_Veff_Liquid(j,1:numHARP2ReffBins,1:numHARP2VeffBins))
    enddo
    Reff_vs_Veff_Liquid(1:nPoints,1:numHARP2ReffBins,1:numHARP2VeffBins) = 100._wp *      &
         Reff_vs_Veff_Liquid(1:nPoints,1:numHARP2ReffBins,1:numHARP2VeffBins)/nSubCols

  end subroutine harp2_column

  ! ########################################################################################
  ! Scattering angle (degrees) for solar zenith cosine mu0, view zenith cosine mu and
  ! relative azimuth relAz (degrees) between the directions to the sun and to the sensor
  ! (relAz = 0: sensor on the same side as the sun, i.e. backscattering).
  ! ########################################################################################
  elemental function scattering_angle(mu0, mu, relAz)
    real(wp),intent(in) :: mu0, mu, relAz
    real(wp)            :: scattering_angle
    real(wp)            :: cosTheta

    cosTheta = -mu0*mu - sqrt(max(0._wp, 1._wp - mu0**2))*sqrt(max(0._wp, 1._wp - mu**2))*  &
               cos(relAz*pi/180._wp)
    scattering_angle = acos(max(-1._wp, min(1._wp, cosTheta)))*180._wp/pi
  end function scattering_angle

  ! ########################################################################################
  ! Single-scattering polarized reflectance of a layered column (black surface)
  ! ########################################################################################
  subroutine single_scattering_polarized_reflectance(nLevels, nWin, tauLiq, tauIce,      &
       tauRay, reff, veff, airMass, geoNorm, mP12Ray, F, Rp)
    ! INPUTS
    integer,intent(in) :: nLevels, nWin
    real(wp),intent(in),dimension(nLevels) :: tauLiq, tauIce, tauRay, reff, veff
    real(wp),intent(in),dimension(nWin) :: airMass, geoNorm, mP12Ray
    real(wp),intent(in),dimension(nWin,nLUT_re,nLUT_ve) :: F
    ! OUTPUTS
    real(wp),intent(out),dimension(nWin) :: Rp
    ! LOCAL VARIABLES
    integer :: k, ir, iv
    real(wp) :: dtau, tauAbove, wr, wv, ssa
    real(wp),dimension(nWin) :: source, mP12Liq, layerFactor

    Rp(1:nWin) = 0._wp
    tauAbove   = 0._wp
    do k = 1, nLevels
       dtau = tauLiq(k) + tauIce(k) + tauRay(k)
       if (dtau <= 0._wp) cycle

       source(1:nWin) = tauRay(k)*mP12Ray(1:nWin)
       if (tauLiq(k) > 0._wp) then
          call lut_weights(reff(k), veff(k), ir, iv, wr, wv)
          mP12Liq(1:nWin) = (1._wp-wr)*(1._wp-wv)*F(1:nWin,ir,  iv  ) +                  &
                                    wr *(1._wp-wv)*F(1:nWin,ir+1,iv  ) +                  &
                            (1._wp-wr)*        wv *F(1:nWin,ir,  iv+1) +                  &
                                    wr *        wv *F(1:nWin,ir+1,iv+1)
          ssa = (1._wp-wr)*(1._wp-wv)*LUT_ssa(ir,iv  ) + wr*(1._wp-wv)*LUT_ssa(ir+1,iv  ) + &
                (1._wp-wr)*        wv *LUT_ssa(ir,iv+1) + wr*        wv *LUT_ssa(ir+1,iv+1)
          source(1:nWin) = source(1:nWin) + tauLiq(k)*ssa*mP12Liq(1:nWin)
       endif

       ! Attenuation from the top of the atmosphere and escape from the layer
       where(dtau*airMass(1:nWin) > 1.e-6_wp)
          layerFactor(1:nWin) = exp(-tauAbove*airMass(1:nWin)) *                         &
                                (1._wp - exp(-dtau*airMass(1:nWin)))/dtau
       elsewhere
          layerFactor(1:nWin) = exp(-tauAbove*airMass(1:nWin))*airMass(1:nWin)
       endwhere
       Rp(1:nWin) = Rp(1:nWin) + source(1:nWin)*layerFactor(1:nWin)

       tauAbove = tauAbove + dtau
       ! Deeper layers do not contribute (airMass >= 2)
       if (tauAbove > 20._wp) exit
    enddo
    Rp(1:nWin) = Rp(1:nWin)/geoNorm(1:nWin)

  end subroutine single_scattering_polarized_reflectance

  ! ########################################################################################
  ! Parametric cloudbow fit: z = A*(-P12(re,ve)) + B cos^2 + C over all LUT nodes
  ! ########################################################################################
  subroutine cloudbow_retrieval(nWin, z, basis1, basis2, Ftil, FtilNorm2, flag, re, ve)
    ! INPUTS
    integer,intent(in) :: nWin
    real(wp),intent(in),dimension(nWin) :: z, basis1, basis2
    real(wp),intent(in),dimension(nWin,nLUT_re,nLUT_ve) :: Ftil
    real(wp),intent(in),dimension(nLUT_re,nLUT_ve) :: FtilNorm2
    ! OUTPUTS
    integer, intent(out) :: flag
    real(wp),intent(out) :: re, ve       ! re in microns
    ! LOCAL VARIABLES
    real(wp),dimension(nWin) :: ztil
    real(wp),dimension(nLUT_re,nLUT_ve) :: proj, ssr
    real(wp) :: ztilNorm2, amplitude
    integer  :: loc(2), ir, iv

    ! Remove the smooth terms from the signal. The residual of the full fit at node n is
    ! |ztil|^2 - (Ftil_n . ztil)^2/|Ftil_n|^2 and the cloudbow amplitude is
    ! A_n = (Ftil_n . ztil)/|Ftil_n|^2
    ztil(1:nWin) = z(1:nWin) - dot_product(basis1,z)*basis1(1:nWin) -                    &
                               dot_product(basis2,z)*basis2(1:nWin)
    ztilNorm2 = dot_product(ztil, ztil)

    do iv = 1, nLUT_ve
       do ir = 1, nLUT_re
          proj(ir,iv) = dot_product(Ftil(1:nWin,ir,iv), ztil(1:nWin))
       enddo
    enddo
    ! Only positive amplitudes (a cloudbow, not its mirror image) are admissible
    where(proj > 0._wp .and. FtilNorm2 > 0._wp)
       ssr = ztilNorm2 - proj**2/FtilNorm2
    elsewhere
       ssr = huge(1._wp)
    endwhere
    loc = minloc(ssr)
    ir  = loc(1)
    iv  = loc(2)

    re = R_UNDEF
    ve = R_UNDEF
    if (ssr(ir,iv) >= huge(1._wp)) then
       flag = harp2_flagNoCloudbow
       return
    endif
    amplitude = proj(ir,iv)/FtilNorm2(ir,iv)
    if (amplitude < cloudbow_AmplitudeMin) then
       flag = harp2_flagNoCloudbow
       return
    endif
    if (ztilNorm2 <= 0._wp .or. 1._wp - ssr(ir,iv)/ztilNorm2 < fit_QualityMin .or.       &
        ir == 1 .or. ir == nLUT_re) then
       flag = harp2_flagFitFailed
       return
    endif

    ! Parabolic refinement of the minimum along re and ve
    flag = harp2_flagCloudbow
    re   = parabolic_minimum(LUT_re(ir-1), LUT_re(ir), LUT_re(ir+1),                     &
                             ssr(ir-1,iv), ssr(ir,iv), ssr(ir+1,iv))
    if (iv > 1 .and. iv < nLUT_ve) then
       if (ssr(ir,iv-1) < huge(1._wp) .and. ssr(ir,iv+1) < huge(1._wp)) then
          ve = parabolic_minimum(LUT_ve(iv-1), LUT_ve(iv), LUT_ve(iv+1),                 &
                                 ssr(ir,iv-1), ssr(ir,iv), ssr(ir,iv+1))
       else
          ve = LUT_ve(iv)
       endif
    else
       ve = LUT_ve(iv)
    endif

  end subroutine cloudbow_retrieval

  ! ########################################################################################
  ! Abscissa of the vertex of the parabola through three points, limited to [x1,x3]
  ! ########################################################################################
  pure function parabolic_minimum(x1, x2, x3, f1, f2, f3)
    real(wp),intent(in) :: x1, x2, x3, f1, f2, f3
    real(wp)            :: parabolic_minimum
    real(wp)            :: num, den

    parabolic_minimum = x2
    if (f1 >= huge(1._wp) .or. f3 >= huge(1._wp)) return
    num = (x2-x1)**2*(f2-f3) - (x2-x3)**2*(f2-f1)
    den = (x2-x1)*(f2-f3) - (x2-x3)*(f2-f1)
    if (den /= 0._wp) parabolic_minimum = max(x1, min(x3, x2 - 0.5_wp*num/den))
  end function parabolic_minimum

  ! ########################################################################################
  ! Orthonormal basis (Gram-Schmidt) of {1, cos^2(Theta)} over the window angles
  ! ########################################################################################
  subroutine smooth_basis(nWin, theta, basis1, basis2)
    integer,intent(in) :: nWin
    real(wp),intent(in),dimension(nWin) :: theta
    real(wp),intent(out),dimension(nWin) :: basis1, basis2
    real(wp) :: norm2

    basis1(1:nWin) = 1._wp/sqrt(real(nWin, wp))
    basis2(1:nWin) = cos(theta(1:nWin)*pi/180._wp)**2
    basis2(1:nWin) = basis2(1:nWin) - dot_product(basis1, basis2)*basis1(1:nWin)
    norm2 = dot_product(basis2, basis2)
    if (norm2 > 0._wp) then
       basis2(1:nWin) = basis2(1:nWin)/sqrt(norm2)
    else
       basis2(1:nWin) = 0._wp
    endif
  end subroutine smooth_basis

  ! ########################################################################################
  ! Remove the projection on the smooth basis from nVec vectors of length nWin
  ! ########################################################################################
  subroutine remove_smooth(nWin, nVec, basis1, basis2, F, Ftil)
    integer,intent(in) :: nWin, nVec
    real(wp),intent(in),dimension(nWin) :: basis1, basis2
    real(wp),intent(in),dimension(nWin,nVec) :: F
    real(wp),intent(out),dimension(nWin,nVec) :: Ftil
    integer :: n

    do n = 1, nVec
       Ftil(1:nWin,n) = F(1:nWin,n) - dot_product(basis1, F(1:nWin,n))*basis1(1:nWin) -  &
                                      dot_product(basis2, F(1:nWin,n))*basis2(1:nWin)
    enddo
  end subroutine remove_smooth

  ! ########################################################################################
  ! -P12 of every LUT node, linearly interpolated to the requested scattering angles
  ! ########################################################################################
  subroutine lut_at_angles(nWin, theta, F)
    integer,intent(in) :: nWin
    real(wp),intent(in),dimension(nWin) :: theta
    real(wp),intent(out),dimension(nWin,nLUT_re,nLUT_ve) :: F
    integer  :: j, it
    real(wp) :: dTheta, w

    dTheta = (LUT_theta(nLUT_theta) - LUT_theta(1))/(nLUT_theta - 1)
    do j = 1, nWin
       it = min(nLUT_theta - 1, max(1, 1 + int((theta(j) - LUT_theta(1))/dTheta)))
       w  = max(0._wp, min(1._wp, (theta(j) - LUT_theta(it))/dTheta))
       F(j,1:nLUT_re,1:nLUT_ve) = (1._wp - w)*LUT_mP12(it,  1:nLUT_re,1:nLUT_ve) +       &
                                          w *LUT_mP12(it+1,1:nLUT_re,1:nLUT_ve)
    enddo
  end subroutine lut_at_angles

  ! ########################################################################################
  ! Bilinear interpolation indices and weights in (re, ve); values outside the LUT are
  ! clamped to its edges
  ! ########################################################################################
  pure subroutine lut_weights(re, ve, ir, iv, wr, wv)
    real(wp),intent(in)  :: re, ve
    integer, intent(out) :: ir, iv
    real(wp),intent(out) :: wr, wv
    real(wp) :: dre

    dre = (LUT_re(nLUT_re) - LUT_re(1))/(nLUT_re - 1)
    ir  = min(nLUT_re - 1, max(1, 1 + int((re - LUT_re(1))/dre)))
    wr  = max(0._wp, min(1._wp, (re - LUT_re(ir))/dre))

    iv = 1
    do while (iv < nLUT_ve - 1 .and. ve > LUT_ve(iv+1))
       iv = iv + 1
    enddo
    wv = max(0._wp, min(1._wp, (ve - LUT_ve(iv))/(LUT_ve(iv+1) - LUT_ve(iv))))
  end subroutine lut_weights

end module mod_harp2_sim
